### ISSUE TITLE
ipfs-update in dockerfile failing - cannot load crypto/ed25519

### ISSUE THREAD

**Issue by mitra42** [ipfs/ipfs-update#114]
ipfs-update is failing again in dockers ....  symptom is a line like
```
build github.com/ipfs/ipfs-update: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519
```
during the go get of ipfs-update. 

I'll post more details below ....

**Comment by mitra42** [comment]
Dockerfile extracts .... 
```
FROM ubuntu:rolling
...
ENV GOPATH=/go
ENV PATH=${GOPATH}/bin:${PATH}
...
RUN apt-get -y install golang
...
RUN cd ${GOPATH} \
    GO111MODULE=on go get -u -v github.com/ipfs/ipfs-update \
    && ipfs-update install latest \
    || echo "ERROR: ===== ipfs-update failing again, will run without enabling IPFS ====="
```

**Comment by mitra42** [comment]
Suggestions elsewhere in https://github.com/micro/go-micro/issues/748 suggest you need Go 1.13 to solve this (the other suggestions there didn't work) BUT ubuntu is still on 1.12, 

Is there a solution or is ipfs-update no longer docker compatible till ubuntu ups the Go version to 1.13 ?

**Comment by Stebalien** [comment]
Don't pass `-u` to `go get`. That tells go to update the dependencies (which won't work on go 1.12).

**Comment by mitra42** [comment]
Thanks - that fixed it
